sensors:
  - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
    point_cloud_topic: /camera/depth_registered/points
    max_range: 2.5 # default: 5.0
    point_subsample: 1 # default: 1
    padding_offset: 0.0 # default: 0.1
    padding_scale: 1.0 # default: 1.0
    filtered_cloud_topic: filtered_cloud
