controller_list:
  - name: fake_manipulator_controller
    joints:
      - sternoclavicular_joint
      - shoulder_joint
      - shoulderRot_joint
      - elbow_joint
      - WristRot_joint
      - Wrist_joint
  - name: fake_base_controller
    joints:
      - base_x_trans_joint
      - base_y_trans_joint
      - base_revolute_joint
      - sternoclavicular_joint
      - shoulder_joint
      - shoulderRot_joint
      - elbow_joint
      - WristRot_joint
      - Wrist_joint
  - name: fake_gripper_controller
    joints:
      - robotiq_85_left_knuckle_joint